namespace Rexo.Execution;

using Rexo.Core.Models;

internal sealed class SarifBuiltinModule : IConfigBuiltinModule
{
    internal const string DefaultTargetsRelativePath = "msbuild/Rexo.Sarif.targets";

    // Injected via /p:CustomAfterMicrosoftCommonTargets so every project (and every TFM inner
    // build) writes its own SARIF log; a single command-line ErrorLog would be shared and
    // overwritten because global properties are not evaluated per project.
    internal const string SarifTargetsContent = """
        <Project>
          <!-- Generated by Rexo (builtin:dotnet-sarif-targets). Do not edit. -->
          <PropertyGroup Condition="'$(RexoSarifDirectory)' != ''">
            <RexoSarifVersion Condition="'$(RexoSarifVersion)' == ''">2.1</RexoSarifVersion>
            <_RexoSarifName>$(MSBuildProjectName)</_RexoSarifName>
            <_RexoSarifName Condition="'$(TargetFramework)' != ''">$(_RexoSarifName).$(TargetFramework)</_RexoSarifName>
            <ErrorLog>$([System.IO.Path]::Combine('$(RexoSarifDirectory)', '$(_RexoSarifName).sarif')),version=$(RexoSarifVersion)</ErrorLog>
          </PropertyGroup>
        </Project>
        """;

    public void Register(BuiltinRegistry registry, ConfigBuiltinModuleContext context)
    {
        registry.Register("builtin:dotnet-sarif-targets", async (step, ctx, ct) =>
        {
            var stepId = step.Id ?? "dotnet-sarif-targets";
            var targetsPath = ResolvePath(context.RepositoryRoot, GetOption(ctx, "path"));
            if (targetsPath is null)
            {
                var temp = ctx.ResolvedOutputs.TryGetValue("temp", out var tempValue) ? tempValue?.ToString() : null;
                if (string.IsNullOrWhiteSpace(temp))
                {
                    return Fail(stepId, "No 'path' provided and outputs.temp is not configured.");
                }

                targetsPath = ResolvePath(context.RepositoryRoot, Path.Combine(temp, DefaultTargetsRelativePath))!;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(targetsPath)!);
            await File.WriteAllTextAsync(targetsPath, SarifTargetsContent, ct);
            Console.WriteLine($"  Wrote MSBuild SARIF targets: {targetsPath}");

            var outputs = new Dictionary<string, object?> { ["path"] = targetsPath };

            var sarifDirectory = ResolvePath(context.RepositoryRoot, GetOption(ctx, "sarifDirectory"));
            if (sarifDirectory is not null)
            {
                // Clear stale per-project logs from earlier runs so they are not merged again.
                if (Directory.Exists(sarifDirectory))
                {
                    foreach (var stale in Directory.EnumerateFiles(sarifDirectory, "*.sarif", SearchOption.AllDirectories))
                    {
                        File.Delete(stale);
                    }
                }

                Directory.CreateDirectory(sarifDirectory);
                outputs["sarifDirectory"] = sarifDirectory;
            }

            return new StepResult(stepId, true, 0, TimeSpan.Zero, outputs);
        });

        registry.Register("builtin:sarif-merge", async (step, ctx, ct) =>
        {
            var stepId = step.Id ?? "sarif-merge";
            var input = ResolvePath(context.RepositoryRoot, GetOption(ctx, "input"));
            var output = ResolvePath(context.RepositoryRoot, GetOption(ctx, "output"));
            if (input is null || output is null)
            {
                return Fail(stepId, "builtin:sarif-merge requires 'input' and 'output'.");
            }

            var inputFiles = CollectInputs(input);
            var result = await SarifMerger.MergeAsync(
                inputFiles,
                output,
                GetOption(ctx, "category"),
                context.RepositoryRoot,
                ct);

            foreach (var warning in result.Warnings)
            {
                Console.WriteLine($"  Warning: {warning}");
            }

            var message = result.Written
                ? $"Merged {result.InputFiles} SARIF file(s) into {output} ({result.Runs} run(s), {result.Results} result(s))."
                : $"No SARIF 2.1.0 input found in {input}; nothing written.";
            Console.WriteLine($"  {message}");

            return new StepResult(
                stepId,
                true,
                0,
                TimeSpan.Zero,
                new Dictionary<string, object?>
                {
                    ["message"] = message,
                    ["output"] = result.Written ? output : string.Empty,
                    ["inputs"] = result.InputFiles,
                    ["runs"] = result.Runs,
                    ["results"] = result.Results,
                });
        });
    }

    private static List<string> CollectInputs(string input)
    {
        if (File.Exists(input))
        {
            return [input];
        }

        if (!Directory.Exists(input))
        {
            return [];
        }

        return Directory.EnumerateFiles(input, "*.sarif", SearchOption.AllDirectories)
            .Order(StringComparer.Ordinal)
            .ToList();
    }

    private static string? GetOption(Rexo.Core.Models.ExecutionContext ctx, string key) =>
        ctx.Options.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value)
            ? value.Trim()
            : null;

    private static string? ResolvePath(string repositoryRoot, string? path) =>
        path is null
            ? null
            : Path.GetFullPath(Path.IsPathRooted(path) ? path : Path.Combine(repositoryRoot, path));

    private static StepResult Fail(string stepId, string message)
    {
        Console.WriteLine($"  {message}");
        return new StepResult(
            stepId,
            false,
            1,
            TimeSpan.Zero,
            new Dictionary<string, object?> { ["error"] = message });
    }
}
